import type {ModelMetadata} from '../metadata/types';
import type {ValidationOptions} from './engine';

/**
 * Framework-neutral validation issue.
 */
export type ValidationIssue = {
    path: Array<string | number>;
    code: string;
    message: string;
    constraint: string;
    params?: Record<string, unknown>;
};

/**
 * Result returned by validator schemas.
 */
export type ValidationResult<TValue = unknown> =
    | { success: true; data: TValue }
    | { success: false; issues: ValidationIssue[] };

/**
 * Framework-neutral schema generated by a validator adapter.
 */
export interface ValidatorSchema<TValue = unknown> {
    /**
     * Validates input data and returns normalized Decorix validation output.
     *
     * @param value - Unknown input to validate.
     * @param options - Optional group, locale, service, and registry controls.
     * @returns Successful parsed data or normalized validation issues.
     */
    validate(value: unknown, options?: ValidationOptions): ValidationResult<TValue>;

    /**
     * Validates input data asynchronously, resolving async constraints.
     *
     * Optional: adapters that cannot run async validation omit it, and callers
     * should fall back to {@link ValidatorSchema.validate} (see `runSchemaAsync`).
     *
     * @param value - Unknown input to validate.
     * @param options - Optional group, locale, service, and registry controls.
     * @returns Promise of successful parsed data or normalized validation issues.
     */
    validateAsync?(value: unknown, options?: ValidationOptions): Promise<ValidationResult<TValue>>;
}

/**
 * Adapter capable of creating validator schemas from Decorix metadata.
 */
export interface ValidatorAdapter<TSchema extends ValidatorSchema = ValidatorSchema> {
    /**
     * Unique adapter name used by the global registry.
     */
    readonly name: string;

    /**
     * Creates a validator schema for a model.
     *
     * @param metadata - Decorix model metadata.
     * @returns A framework-neutral schema facade.
     */
    createSchema(metadata: ModelMetadata): TSchema;
}

/**
 * Validator adapter reference accepted by generated UI adapters.
 */
export type ValidatorAdapterRef = ValidatorAdapter | string;

export type {ValidationOptions};
