import type {ModelMetadata} from '../metadata/types';

/**
 * Framework-neutral validation issue.
 */
export type ValidationIssue = {
    path: Array<string | number>;
    message: string;
    code?: string;
};

/**
 * Result returned by validator schemas.
 */
export type ValidationResult<TValue = unknown> =
    | { success: true; data: TValue }
    | { success: false; issues: ValidationIssue[] };

/**
 * Framework-neutral schema generated by a validator adapter.
 */
export interface ValidatorSchema<TValue = unknown> {
    /**
     * Validates input data and returns normalized Decorix validation output.
     *
     * @param value - Unknown input to validate.
     * @returns Successful parsed data or normalized validation issues.
     */
    validate(value: unknown): ValidationResult<TValue>;
}

/**
 * Adapter capable of creating validator schemas from Decorix metadata.
 */
export interface ValidatorAdapter<TSchema extends ValidatorSchema = ValidatorSchema> {
    /**
     * Unique adapter name used by the global registry.
     */
    readonly name: string;

    /**
     * Creates a validator schema for a model.
     *
     * @param metadata - Decorix model metadata.
     * @returns A framework-neutral schema facade.
     */
    createSchema(metadata: ModelMetadata): TSchema;
}

/**
 * Validator adapter reference accepted by generated UI adapters.
 */
export type ValidatorAdapterRef = ValidatorAdapter | string;
