import type {ConstraintMetadata, FieldMetadata, FieldType, ModelMetadata, UiMetadata} from '@decorix/core';
import {createConstraintMetadata} from '@decorix/core';
import type {JsonSchema} from './types';

/** Serialized constraint entry shape emitted under `x-decorix-constraints` by the exporter. */
type DecorixConstraintExtension = {
    name: string;
    options?: unknown;
    message?: string;
    groups?: string[];
    async?: true;
};

/**
 * Converts a JSON Schema object into Decorix model metadata.
 *
 * This is the best-effort inverse of {@link toJsonSchema}: standard keywords map
 * back to native constraints, and Decorix-specific `x-decorix-constraints`
 * entries are restored verbatim so that `toJsonSchema(fromJsonSchema(x))` is
 * stable for Decorix-produced schemas. Arbitrary custom validator/predicate
 * functions cannot be reconstructed and are preserved as the `'[function]'`
 * sentinel.
 *
 * Security note: a `pattern`/`x-decorix-constraints` `RegExp` in `schema` is
 * turned into a live `RegExp` re-run on every validation. Only pass schemas
 * you trust (generated by {@link toJsonSchema} or otherwise audited) — a
 * schema from an untrusted source could carry a catastrophically backtracking
 * pattern (ReDoS).
 *
 * @param schema - JSON Schema draft 2020-12 object with an object root.
 * @returns Framework-neutral model metadata.
 */
export function fromJsonSchema(schema: JsonSchema): ModelMetadata {
    const requiredNames = new Set(schema.required ?? []);
    const fields = Object.entries(schema.properties ?? {}).map(([name, propSchema]) =>
        propertyToField(name, propSchema, requiredNames.has(name))
    );
    const objectConstraints = readConstraintExtensions(schema);
    return {
        name: schema.title ?? 'ImportedModel',
        fields,
        ...(objectConstraints.length ? {objectConstraints} : {})
    };
}

/** Builds field metadata from a single JSON Schema property. */
function propertyToField(name: string, schema: JsonSchema, required: boolean): FieldMetadata {
    const type = detectFieldType(schema);
    const field: FieldMetadata = {name, type, required, constraints: []};

    // Optional fields carry an explicit constraint mirroring the exporter's required rule.
    if (!required) field.constraints.push(createConstraintMetadata('optional'));

    switch (type) {
        case 'enum':
            field.enumValues = enumValues(schema.enum);
            // The enum values double as a constraint so imported models validate like builder-declared enums.
            field.constraints.push(createConstraintMetadata('enum', field.enumValues));
            break;
        case 'array':
            field.item = propertyToField('$item', schema.items ?? {}, true);
            break;
        case 'object':
            field.fields = objectFields(schema);
            break;
        default:
            break;
    }

    applyKeywordConstraints(field, schema);
    // Decorix extension constraints are appended last so their order matches the exporter output.
    field.constraints.push(...readConstraintExtensions(schema));

    const ui = importUi(schema);
    if (ui) field.ui = ui;
    return field;
}

/** Recurses into an object schema's properties, honoring the nested required array. */
function objectFields(schema: JsonSchema): FieldMetadata[] {
    const requiredNames = new Set(schema.required ?? []);
    return Object.entries(schema.properties ?? {}).map(([name, child]) =>
        propertyToField(name, child, requiredNames.has(name))
    );
}

/** Determines the Decorix field type from JSON Schema structure and keywords. */
function detectFieldType(schema: JsonSchema): FieldType {
    const type = Array.isArray(schema.type) ? schema.type[0] : schema.type;
    if (type === 'array') return 'array';
    if (type === 'object' || schema.properties) return 'object';
    if (schema.enum && type === 'string') return 'enum';
    if (type === 'integer') return 'number';
    if (type === 'number') return 'number';
    if (type === 'boolean') return 'boolean';
    // Strings tagged with the date-time format become date fields, mirroring the exporter's base schema.
    if (type === 'string' && schema.format === 'date-time') return 'date';
    return 'string';
}

/** Maps standard JSON Schema validation keywords to native Decorix constraints. */
function applyKeywordConstraints(field: FieldMetadata, schema: JsonSchema): void {
    const add = (name: string, options?: unknown) => field.constraints.push(createConstraintMetadata(name, options));

    // Integer is expressed as a JSON Schema type but carried as a numeric constraint in Decorix.
    if ((Array.isArray(schema.type) ? schema.type[0] : schema.type) === 'integer') add('integer');

    if (schema.minLength !== undefined) add('minLength', schema.minLength);
    if (schema.maxLength !== undefined) add('maxLength', schema.maxLength);
    if (schema.pattern !== undefined) add('pattern', new RegExp(schema.pattern));
    applyFormatConstraint(field, schema.format);

    if (schema.minimum !== undefined) add('min', schema.minimum);
    if (schema.maximum !== undefined) add('max', schema.maximum);
    if (schema.multipleOf !== undefined) add('multipleOf', schema.multipleOf);

    if (schema.minItems !== undefined) add('minItems', schema.minItems);
    if (schema.maxItems !== undefined) add('maxItems', schema.maxItems);
    if (schema.uniqueItems === true) add('uniqueItems');

    // A top-level `enum` on a non-enum field is an allow-list; `not.enum` is a deny-list.
    if (schema.enum && field.type !== 'enum') add('oneOf', [...schema.enum]);
    if (schema.not?.enum) add('notOneOf', [...schema.not.enum]);
}

/** Maps a JSON Schema `format` to its native string constraint, ignoring type-marker formats. */
function applyFormatConstraint(field: FieldMetadata, format: string | undefined): void {
    if (format === 'email') field.constraints.push(createConstraintMetadata('email'));
    else if (format === 'uri') field.constraints.push(createConstraintMetadata('url'));
    else if (format === 'uuid') field.constraints.push(createConstraintMetadata('uuid'));
    // `date-time` is consumed by field-type detection and never becomes a constraint.
}

/** Reads and deserializes `x-decorix-constraints` entries on a schema node. */
function readConstraintExtensions(schema: JsonSchema): ConstraintMetadata[] {
    const raw = schema['x-decorix-constraints'];
    if (!Array.isArray(raw)) return [];
    return (raw as DecorixConstraintExtension[]).map(deserializeConstraintExtension);
}

/** Restores a serialized constraint extension to canonical constraint metadata. */
function deserializeConstraintExtension(entry: DecorixConstraintExtension): ConstraintMetadata {
    return createConstraintMetadata(
        entry.name,
        entry.options === undefined ? undefined : deserializeOption(entry.options),
        {message: entry.message, groups: entry.groups}
    );
}

/** Inverse of the exporter's option serialization for RegExp, arrays, and nested objects. */
function deserializeOption(option: unknown): unknown {
    if (Array.isArray(option)) return option.map(deserializeOption);
    if (isRegExpLike(option)) return new RegExp(option.source, option.flags);
    if (typeof option === 'object' && option !== null) {
        return Object.fromEntries(Object.entries(option).map(([key, value]) => [key, deserializeOption(value)]));
    }
    // Primitives, ISO date strings, and the '[function]' sentinel are preserved verbatim.
    return option;
}

/** Detects the `{source, flags}` shape the exporter uses for RegExp options. */
function isRegExpLike(value: unknown): value is {source: string; flags: string} {
    return (
        typeof value === 'object' &&
        value !== null &&
        typeof (value as {source?: unknown}).source === 'string' &&
        typeof (value as {flags?: unknown}).flags === 'string' &&
        Object.keys(value).length === 2
    );
}

/** Reconstructs UI metadata from JSON Schema annotations and Decorix extensions. */
function importUi(schema: JsonSchema): UiMetadata | undefined {
    const ui: UiMetadata = {};
    if (schema.title !== undefined) ui.label = schema.title;
    if (schema.description !== undefined) ui.description = schema.description;
    if (schema.readOnly !== undefined) ui.readonly = schema.readOnly;
    const placeholder = schema['x-decorix-placeholder'];
    if (placeholder !== undefined) ui.placeholder = placeholder as string;
    const hidden = schema['x-decorix-hidden'];
    if (hidden !== undefined) ui.hidden = hidden as boolean;
    const order = schema['x-decorix-order'];
    if (order !== undefined) ui.order = order as number;
    const group = schema['x-decorix-group'];
    if (group !== undefined) ui.group = group as string;
    return Object.keys(ui).length ? ui : undefined;
}

/** Narrows an imported enum list to the non-empty tuple Decorix expects. */
function enumValues(values: readonly string[] | undefined): readonly [string, ...string[]] {
    if (values && values.length) return values as readonly [string, ...string[]];
    return [''];
}
